[package]
name = "netio"
version = "0.1.0"
authors = ["theCow61 <theCow61@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
